spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://127.0.0.1:5432/blog
        username: postgres
        password: dl123
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        properties:
            hibernate:
                temp:
                    use_jdbc_metadata_defaults: false
        open-in-view: true
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
    sleuth:
        sampler:
            probability: 1
    zipkin:
        base-url: http://127.0.0.1:9000


eureka:
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8002/eureka/

server:
    port: 8112

