spring:
  application:
    name: blog-turbine
  cloud:
    config:
      label: master
      profile: dev
      #      discovery:
      #        enabled: true
      #        service-id: blog-config-server
      uri: http://localhost:8020/
