eureka:
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8002/eureka/
server:
    port: 8012
spring:
    datasource:
        password: dl123
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://127.0.0.1:5432/blog
        username: postgres
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        properties:
            hibernate:
                temp:
                    use_jdbc_metadata_defaults: false
test:
    test: hello scca
