spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/blog
    username: postgres
    password: dl123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8002/eureka/

server:
  port: 8012

